name: Build and Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      run: dotnet restore --runtime win-x64 /p:BuildNumber=${{ github.run_number }}
    
    - name: Build
      run: dotnet build --configuration Release --runtime win-x64 --no-restore /p:BuildNumber=${{ github.run_number }}
    
    - name: Publish
      run: dotnet publish --configuration Release --no-build --self-contained -r win-x64 -p:PublishSingleFile=true -p:BuildNumber=${{ github.run_number }} -o ./publish

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ArbitraryImageResizer
        path: ./publish/ArbitraryImageResizer.exe

  release:
    needs: build
    runs-on: windows-latest

    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v3
      with:
        name: ArbitraryImageResizer
      
    - name: Create Release
      run: |
        $releaseResponse = Invoke-RestMethod `
        -Headers @{Authorization="token ${{ secrets.RELEASE_TOKEN }}"} `
        -Uri https://api.github.com/repos/${{ github.repository }}/releases `
        -Method POST `
        -Body (ConvertTo-Json @{
            tag_name = "v1.0.0"
            name = "Release v1.0.0"
            draft = $false
            prerelease = $false
        })
        $uploadUrl = $releaseResponse.upload_url -replace "{?name,label}", "?name=ArbitraryImageResizer.exe"
        Invoke-RestMethod `
        -Headers @{Authorization="token ${{ secrets.RELEASE_TOKEN }}"; "Content-Type"="application/octet-stream"} `
        -Uri $uploadUrl `
        -Method POST `
        -InFile ./arbitrary-image-resizer/ArbitraryImageResizer.exe
      shell: pwsh

